### ISSUE TITLE
Consider removing audit log

### ISSUE THREAD

**Issue by rkujawa** [xh3n1/cover-your-tracks#1]
Hi. While I realise this list is probably for personal use, I have the following suggestion.

Besides removing authentication log and user's history files, it is necessary to also remove audit log (i.e. /var/log/audit/ on most distributions). It is deployed by default on many distros and could be easily used to discover what kind of administrative operations were executed on the machine. Besides, if additionally configured by the admin, it can even be used to recover whole command history of both unprivileged users and root. Many people do use audit subsystem for this purpose, since bash history is not really considered a security feature (just a convenience for the user).

**Comment by xh3n1** [comment]
@rkujawa feel free to create a PR :)

**Comment by rkujawa** [comment]
Will do.

**Comment by rkujawa** [comment]
Btw. should the "linux" file, perhaps be formatted with Markdown for easier reading?

**Comment by xh3n1** [comment]
@rkujawa yes!
